-- Accepted-data critical checks and KPI-derived warning generation.
-- The six rejected pre-load fixtures remain separate and are not recreated here.

PRAGMA foreign_keys = ON;

BEGIN;

-- Remove only findings generated by this SQL so reruns are deterministic.
DELETE FROM validation_issues
WHERE issue_id LIKE 'SQL-C-%' OR issue_id LIKE 'WARN-%';

-- These critical SELECTs are expected to return zero rows because the accepted
-- SQLite tables enforce required fields, keys, relationships, and value ranges.
INSERT INTO validation_issues (
    issue_id, reporting_period, source_table, record_key, rule_code, severity,
    issue_description, detected_at, issue_status, assigned_owner,
    resolution_note, resolved_at
)
SELECT
    'SQL-C-MISSING-BRANCH-' || customer_id || '-' || replace(reporting_period, '-', ''),
    reporting_period, 'customer_period_assignments', customer_id || '|' || reporting_period,
    'MISSING_BRANCH_ID', 'CRITICAL', 'Accepted assignment has no home branch.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM customer_period_assignments
WHERE home_branch_id IS NULL OR trim(home_branch_id) = ''

UNION ALL
SELECT
    'SQL-C-BROKEN-ACCOUNT-' || a.account_id || '-' || replace(a.reporting_period, '-', ''),
    a.reporting_period, 'accounts', a.account_id || '|' || a.reporting_period,
    'INVALID_CUSTOMER_RELATIONSHIP', 'CRITICAL', 'Accepted account has no matching customer.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM accounts a
LEFT JOIN customers c ON c.customer_id = a.customer_id
WHERE c.customer_id IS NULL

UNION ALL
SELECT
    'SQL-C-BROKEN-LOAN-' || l.loan_id || '-' || replace(l.reporting_period, '-', ''),
    l.reporting_period, 'loans', l.loan_id || '|' || l.reporting_period,
    'INVALID_CUSTOMER_RELATIONSHIP', 'CRITICAL', 'Accepted loan has no matching customer.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM loans l
LEFT JOIN customers c ON c.customer_id = l.customer_id
WHERE c.customer_id IS NULL

UNION ALL
SELECT
    'SQL-C-BROKEN-TRANSACTION-' || t.transaction_id,
    t.reporting_period, 'transactions', t.transaction_id,
    'INVALID_ACCOUNT_RELATIONSHIP', 'CRITICAL', 'Accepted transaction has no matching account-period.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM transactions t
LEFT JOIN accounts a
  ON a.account_id = t.account_id
 AND a.reporting_period = t.reporting_period
WHERE a.account_id IS NULL

UNION ALL
SELECT
    'SQL-C-NEGATIVE-LOAN-' || loan_id || '-' || replace(reporting_period, '-', ''),
    reporting_period, 'loans', loan_id || '|' || reporting_period,
    'NEGATIVE_OUTSTANDING_BALANCE', 'CRITICAL', 'Accepted loan balance is negative.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM loans
WHERE outstanding_principal < 0

UNION ALL
SELECT
    'SQL-C-DUPLICATE-KPI-' || branch_id || '-' || replace(reporting_period, '-', '') || '-' || kpi_id,
    reporting_period, 'monthly_branch_kpis', branch_id || '|' || reporting_period || '|' || kpi_id,
    'DUPLICATE_BRANCH_MONTH_KPI', 'CRITICAL', 'Accepted KPI output contains a duplicate key.',
    '2026-08-28T14:05:00', 'OPEN', 'Reporting Analyst', NULL, NULL
FROM monthly_branch_kpis
GROUP BY branch_id, reporting_period, kpi_id
HAVING COUNT(*) > 1

UNION ALL
SELECT
    'SQL-C-MISSING-PERIOD-' || source_table || '-' || record_key,
    COALESCE(reporting_period, (SELECT MAX(reporting_period) FROM reporting_cycle_status)),
    source_table,
    record_key,
    'MISSING_REPORTING_PERIOD', 'CRITICAL',
    'Accepted record has no reporting period.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM (
    SELECT 'customer_period_assignments' AS source_table, customer_id AS record_key, reporting_period FROM customer_period_assignments
    UNION ALL SELECT 'accounts', account_id, reporting_period FROM accounts
    UNION ALL SELECT 'loans', loan_id, reporting_period FROM loans
    UNION ALL SELECT 'transactions', transaction_id, reporting_period FROM transactions
)
WHERE reporting_period IS NULL OR trim(reporting_period) = ''

UNION ALL
SELECT
    'SQL-C-DUPLICATE-KEY-' || source_table || '-' || record_key,
    reporting_period,
    source_table,
    record_key,
    'DUPLICATE_PRIMARY_IDENTIFIER', 'CRITICAL',
    'Accepted table contains a duplicate primary key.',
    '2026-08-28T14:05:00', 'OPEN', 'Data Owner', NULL, NULL
FROM (
    SELECT 'customer_period_assignments' AS source_table,
           customer_id || '|' || reporting_period AS record_key,
           reporting_period
    FROM customer_period_assignments
    GROUP BY customer_id, reporting_period HAVING COUNT(*) > 1
    UNION ALL
    SELECT 'accounts', account_id || '|' || reporting_period, reporting_period
    FROM accounts GROUP BY account_id, reporting_period HAVING COUNT(*) > 1
    UNION ALL
    SELECT 'loans', loan_id || '|' || reporting_period, reporting_period
    FROM loans GROUP BY loan_id, reporting_period HAVING COUNT(*) > 1
    UNION ALL
    SELECT 'customers', customer_id, (SELECT MAX(reporting_period) FROM reporting_cycle_status)
    FROM customers GROUP BY customer_id HAVING COUNT(*) > 1
    UNION ALL
    SELECT 'transactions', transaction_id, reporting_period
    FROM transactions GROUP BY transaction_id HAVING COUNT(*) > 1
);

-- Movement warnings use the calculated value, not an adjusted reported value.
WITH history AS (
    SELECT
        branch_id,
        reporting_period,
        kpi_id,
        calculated_value,
        LAG(calculated_value) OVER (
            PARTITION BY branch_id, kpi_id
            ORDER BY reporting_period
        ) AS previous_value
    FROM monthly_branch_kpis
    WHERE kpi_id IN (
        'DEPOSIT_VOLUME', 'LOAN_PORTFOLIO', 'TRANSACTION_COUNT',
        'NEW_CUSTOMERS', 'ACTIVE_CUSTOMERS'
    )
),
movements AS (
    SELECT *,
           CASE
               WHEN previous_value IS NULL OR previous_value = 0 THEN NULL
               ELSE (calculated_value - previous_value) / previous_value * 100.0
           END AS movement_pct
    FROM history
),
flagged AS (
    SELECT *,
           CASE kpi_id
               WHEN 'ACTIVE_CUSTOMERS' THEN 10.0
               ELSE 20.0
           END AS threshold_pct
    FROM movements
    WHERE movement_pct IS NOT NULL
      AND ABS(movement_pct) > CASE kpi_id WHEN 'ACTIVE_CUSTOMERS' THEN 10.0 ELSE 20.0 END
      AND (
          kpi_id <> 'NEW_CUSTOMERS'
          OR ABS(calculated_value - previous_value) >= 5
      )
)
INSERT INTO validation_issues (
    issue_id, reporting_period, source_table, record_key, rule_code, severity,
    issue_description, detected_at, issue_status, assigned_owner,
    resolution_note, resolved_at
)
SELECT
    'WARN-' || branch_id || '-' || replace(reporting_period, '-', '') || '-' || kpi_id || '-MOM',
    reporting_period,
    'monthly_branch_kpis',
    branch_id || '|' || reporting_period || '|' || kpi_id,
    CASE kpi_id
        WHEN 'DEPOSIT_VOLUME' THEN 'WARN_DEPOSIT_VOLUME_MOM_20'
        WHEN 'LOAN_PORTFOLIO' THEN 'WARN_LOAN_PORTFOLIO_MOM_20'
        WHEN 'TRANSACTION_COUNT' THEN 'WARN_TRANSACTION_COUNT_MOM_20'
        WHEN 'NEW_CUSTOMERS' THEN 'WARN_NEW_CUSTOMERS_MOM_20'
        WHEN 'ACTIVE_CUSTOMERS' THEN 'WARN_ACTIVE_CUSTOMERS_MOM_10'
    END,
    'WARNING',
    kpi_id || ' changed by ' || printf('%.1f', movement_pct) || '%; threshold is ' || printf('%.1f', threshold_pct) || '%.'
        || CASE WHEN kpi_id = 'NEW_CUSTOMERS' THEN ' Absolute count change is at least 5.' ELSE '' END,
    '2026-08-28T14:05:00',
    'UNDER_REVIEW',
    'Branch Manager',
    'Synthetic management-threshold warning awaiting review; value retained.',
    NULL
FROM flagged;

-- Default Rate level warning.
INSERT INTO validation_issues (
    issue_id, reporting_period, source_table, record_key, rule_code, severity,
    issue_description, detected_at, issue_status, assigned_owner,
    resolution_note, resolved_at
)
SELECT
    'WARN-' || branch_id || '-' || replace(reporting_period, '-', '') || '-DEFAULT-RATE',
    reporting_period,
    'monthly_branch_kpis',
    branch_id || '|' || reporting_period || '|DEFAULT_RATE',
    'WARN_DEFAULT_RATE_8',
    'WARNING',
    'Default Rate is ' || printf('%.1f', calculated_value) || '%; threshold is 8.0%.',
    '2026-08-28T14:05:00', 'UNDER_REVIEW', 'Branch Manager',
    'Synthetic management-threshold warning awaiting review; value retained.', NULL
FROM monthly_branch_kpis
WHERE kpi_id = 'DEFAULT_RATE'
  AND calculated_value > 8.0;

-- Zero eligible posted transaction activity.
INSERT INTO validation_issues (
    issue_id, reporting_period, source_table, record_key, rule_code, severity,
    issue_description, detected_at, issue_status, assigned_owner,
    resolution_note, resolved_at
)
SELECT
    'WARN-' || branch_id || '-' || replace(reporting_period, '-', '') || '-ZERO-TRANSACTIONS',
    reporting_period,
    'monthly_branch_kpis',
    branch_id || '|' || reporting_period || '|TRANSACTION_COUNT',
    'WARN_ZERO_TRANSACTION_COUNT',
    'WARNING',
    'Transaction Count is zero.',
    '2026-08-28T14:05:00', 'UNDER_REVIEW', 'Branch Manager',
    'Synthetic zero-activity warning awaiting review; zero retained.', NULL
FROM monthly_branch_kpis
WHERE kpi_id = 'TRANSACTION_COUNT'
  AND calculated_value = 0;

-- Demonstrate one completed warning-review period. The period is selected
-- deterministically as the warning-only period with the fewest warning rows.
UPDATE validation_issues
SET issue_status = 'ACCEPTED_WARNING',
    resolution_note = 'Reviewed and explained for the synthetic case; KPI value retained.',
    resolved_at = '2026-08-28T15:00:00'
WHERE severity = 'WARNING'
  AND reporting_period = (
      SELECT v.reporting_period
      FROM validation_issues v
      WHERE v.severity = 'WARNING'
        AND NOT EXISTS (
            SELECT 1 FROM validation_issues c
            WHERE c.reporting_period = v.reporting_period
              AND c.severity = 'CRITICAL'
              AND c.issue_status <> 'RESOLVED'
        )
      GROUP BY v.reporting_period
      ORDER BY COUNT(*), v.reporting_period
      LIMIT 1
  );

-- Critical issues block publication. Warnings alone do not set this flag.
UPDATE reporting_cycle_status
SET publication_blocked = CASE
    WHEN EXISTS (
        SELECT 1
        FROM validation_issues v
        WHERE v.reporting_period = reporting_cycle_status.reporting_period
          AND v.severity = 'CRITICAL'
          AND v.issue_status <> 'RESOLVED'
    ) THEN 1 ELSE 0 END;

-- Under-review warnings keep the review workflow open but do not classify the
-- period as critically blocked.
UPDATE reporting_cycle_status
SET branch_review_status = 'IN_PROGRESS',
    branch_review_completed_at = NULL,
    correction_status = 'NOT_STARTED',
    correction_completed_at = NULL,
    report_status = 'NOT_STARTED',
    report_completed_at = NULL
WHERE publication_blocked = 0
  AND EXISTS (
      SELECT 1 FROM validation_issues v
      WHERE v.reporting_period = reporting_cycle_status.reporting_period
        AND v.severity = 'WARNING'
        AND v.issue_status NOT IN ('RESOLVED', 'ACCEPTED_WARNING')
  );

COMMIT;

-- Temporary summaries support exception-rate output in the execution session.
DROP TABLE IF EXISTS temp.dq_source_rates;
CREATE TEMP TABLE dq_source_rates AS
WITH accepted_counts(source_table, accepted_records) AS (
    SELECT 'branches', COUNT(*) FROM branches
    UNION ALL SELECT 'customers', COUNT(*) FROM customers
    UNION ALL SELECT 'customer_period_assignments', COUNT(*) FROM customer_period_assignments
    UNION ALL SELECT 'accounts', COUNT(*) FROM accounts
    UNION ALL SELECT 'loans', COUNT(*) FROM loans
    UNION ALL SELECT 'transactions', COUNT(*) FROM transactions
    UNION ALL SELECT 'monthly_branch_kpis', COUNT(*) FROM monthly_branch_kpis
    UNION ALL SELECT 'reporting_cycle_status', COUNT(*) FROM reporting_cycle_status
),
rejected_counts AS (
    SELECT source_table, COUNT(*) AS rejected_records
    FROM validation_issues
    WHERE severity = 'CRITICAL' AND issue_id LIKE 'INJ-C%'
    GROUP BY source_table
),
failed_counts AS (
    SELECT source_table, COUNT(DISTINCT record_key) AS failed_records
    FROM validation_issues
    WHERE severity = 'CRITICAL'
    GROUP BY source_table
)
SELECT
    a.source_table,
    a.accepted_records + COALESCE(r.rejected_records, 0) AS records_checked,
    COALESCE(f.failed_records, 0) AS records_failed,
    CASE
        WHEN a.accepted_records + COALESCE(r.rejected_records, 0) = 0 THEN NULL
        ELSE COALESCE(f.failed_records, 0) * 100.0
             / (a.accepted_records + COALESCE(r.rejected_records, 0))
    END AS exception_rate_pct
FROM accepted_counts a
LEFT JOIN rejected_counts r USING (source_table)
LEFT JOIN failed_counts f USING (source_table);

DROP TABLE IF EXISTS temp.dq_period_rates;
CREATE TEMP TABLE dq_period_rates AS
WITH periods AS (
    SELECT reporting_period FROM reporting_cycle_status
),
accepted_by_period AS (
    SELECT p.reporting_period,
           (SELECT COUNT(*) FROM branches)
         + (SELECT COUNT(*) FROM customers)
         + (SELECT COUNT(*) FROM customer_period_assignments x WHERE x.reporting_period = p.reporting_period)
         + (SELECT COUNT(*) FROM accounts x WHERE x.reporting_period = p.reporting_period)
         + (SELECT COUNT(*) FROM loans x WHERE x.reporting_period = p.reporting_period)
         + (SELECT COUNT(*) FROM transactions x WHERE x.reporting_period = p.reporting_period)
         + (SELECT COUNT(*) FROM monthly_branch_kpis x WHERE x.reporting_period = p.reporting_period)
         + 1 AS accepted_records
    FROM periods p
),
rejected_by_period AS (
    SELECT reporting_period, COUNT(*) AS rejected_records
    FROM validation_issues
    WHERE severity = 'CRITICAL' AND issue_id LIKE 'INJ-C%'
    GROUP BY reporting_period
),
failed_by_period AS (
    SELECT reporting_period,
           COUNT(DISTINCT source_table || '|' || record_key) AS failed_records
    FROM validation_issues
    WHERE severity = 'CRITICAL'
    GROUP BY reporting_period
)
SELECT
    a.reporting_period,
    a.accepted_records + COALESCE(r.rejected_records, 0) AS records_checked,
    COALESCE(f.failed_records, 0) AS records_failed,
    COALESCE(f.failed_records, 0) * 100.0
        / (a.accepted_records + COALESCE(r.rejected_records, 0)) AS exception_rate_pct
FROM accepted_by_period a
LEFT JOIN rejected_by_period r USING (reporting_period)
LEFT JOIN failed_by_period f USING (reporting_period);

UPDATE reporting_cycle_status
SET overall_dq_exception_rate = (
    SELECT d.exception_rate_pct
    FROM dq_period_rates d
    WHERE d.reporting_period = reporting_cycle_status.reporting_period
);

-- Management warnings are measured separately from data-quality failures.
DROP TABLE IF EXISTS temp.management_warning_summary;
CREATE TEMP TABLE management_warning_summary AS
WITH assessed AS (
    -- Default Rate and Transaction Count are assessed in all 24 periods.
    SELECT branch_id, reporting_period, kpi_id
    FROM monthly_branch_kpis
    WHERE kpi_id IN ('DEFAULT_RATE', 'TRANSACTION_COUNT')
    UNION
    -- Movement-only rules require an available previous period.
    SELECT branch_id, reporting_period, kpi_id
    FROM (
        SELECT branch_id, reporting_period, kpi_id,
               LAG(calculated_value) OVER (
                   PARTITION BY branch_id, kpi_id ORDER BY reporting_period
               ) AS previous_value
        FROM monthly_branch_kpis
        WHERE kpi_id IN ('ACTIVE_CUSTOMERS', 'NEW_CUSTOMERS', 'DEPOSIT_VOLUME', 'LOAN_PORTFOLIO')
    )
    WHERE previous_value IS NOT NULL
),
flagged AS (
    SELECT DISTINCT record_key
    FROM validation_issues
    WHERE severity = 'WARNING'
)
SELECT
    (SELECT COUNT(*) FROM assessed) AS results_assessed,
    (SELECT COUNT(*) FROM flagged) AS results_with_warning,
    (SELECT COUNT(*) FROM validation_issues WHERE severity = 'WARNING') AS warning_issue_count,
    (SELECT COUNT(*) FROM flagged) * 100.0 / (SELECT COUNT(*) FROM assessed) AS management_warning_rate_pct;

-- Publication readiness is derived rather than added to the schema.
-- No separate correction-request entity exists in V1; pending reporting
-- adjustments are used as the implemented correction-disposition check.
DROP TABLE IF EXISTS temp.publication_readiness;
CREATE TEMP TABLE publication_readiness AS
SELECT
    r.reporting_period,
    r.publication_blocked,
    SUM(CASE WHEN v.severity = 'CRITICAL' AND v.issue_status <> 'RESOLVED' THEN 1 ELSE 0 END) AS unresolved_critical_count,
    SUM(CASE WHEN v.severity = 'WARNING' AND v.issue_status NOT IN ('RESOLVED', 'ACCEPTED_WARNING') THEN 1 ELSE 0 END) AS warnings_awaiting_disposition,
    (SELECT COUNT(*) FROM reporting_adjustments a
     WHERE a.reporting_period = r.reporting_period AND a.status = 'PROPOSED') AS pending_adjustment_count,
    CASE
        WHEN SUM(CASE WHEN v.severity = 'CRITICAL' AND v.issue_status <> 'RESOLVED' THEN 1 ELSE 0 END) = 0
         AND SUM(CASE WHEN v.severity = 'WARNING' AND v.issue_status NOT IN ('RESOLVED', 'ACCEPTED_WARNING') THEN 1 ELSE 0 END) = 0
         AND NOT EXISTS (
             SELECT 1 FROM reporting_adjustments a
             WHERE a.reporting_period = r.reporting_period AND a.status = 'PROPOSED'
         )
        THEN 1 ELSE 0
    END AS publication_ready
FROM reporting_cycle_status r
LEFT JOIN validation_issues v USING (reporting_period)
GROUP BY r.reporting_period, r.publication_blocked;
